services:
  postgres:
    image: postgres:18
    container_name: itzamna-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itzamna
    ports:
      - "5432:5432"
    volumes:
      - itzamna_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d itzamna"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  itzamna_pgdata:
